apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-notify
spec:
  replicas: 1
  selector:
    matchLabels:
      name: k8s-notify
  template:
    metadata:
      labels:
        name: k8s-notify
    spec:
      serviceAccountName: k8s-notify
      containers:
        - name: k8s-notify
          # Replace this with the built image name
          image: etsauer/k8s-notify:v0.0.1
          command:
          - k8s-notify
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "k8s-notify"
