kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-chatops
subjects:
- kind: ServiceAccount
  name: k8s-chatops
roleRef:
  kind: Role
  name: k8s-chatops
  apiGroup: rbac.authorization.k8s.io
